DRAW_BOX = false
DRAW_LINE = true

--PLAYER
--PLAYER_SIZE = 10
PLAYER_WIDTH = 16
HALF_WIDTH = PLAYER_WIDTH * 0.5
EYE_HEIGHT = 22
EYE_LOOK_RADIUS = 2.5
PLAYER_SPAWN_Y = 120

PLAYER_ACCELERATION = 500
DRAG_ACCELERATION = 600
PLAYER_GRAVITY = 300
FALLING_GRAVITY = 300

PLAYER_MAX_VELOCITY = 250
PLAYER_MAX_FALL_VELOCITY = 150


PLAYER_JUMP_VELOCITY = 200
PLAYER_MIN_JUMP_VELOCITY = 50

MAX_JUMP_HOLD_DURATION = 300
JUMP_CANCEL_THRESHOLD = 125

GROUND_RAYCAST_LENGTH = 8
GROUND_RAYCAST_OFFSET = 6

--BLOCK
BLOCK_SPAWN_Y = 400

BLOCK_MIN_WIDTH = 50
BLOCK_MAX_WIDTH = 150
BLOCK_HEIGHT = 5

BLOCK_FALL_VELOCITY = 40
TIME_BETWEEN_BLOCK_FALL = 5000
